---
- name: Install common debian packages
  apt:
    pkg: "{{ generic_packages }}"
    state: present

- name: Install qemu-guest-agent
  apt:
    pkg: "{{ qemu_packages }}"
    state: present
  when: setup_qemu
