---
- name: Upgrade RHEL and clones till major release 7
  ansible.builtin.yum:
    update_cache: true
    name: "*"
    state: latest
    exclude: kernel*
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version']|int <= 7

- name: Upgrade RHEL and clones from major release 8
  ansible.builtin.dnf:
    update_cache: true
    name: "*"
    state: latest
    exclude: kernel*
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8

- name: Upgrade Debian and clones
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 1200
    upgrade: dist
  when:
    - ansible_facts['os_family'] == "Debian"
