hosts:
  docker.prod.ff-weingarten.de:
  jump.prod.ff-weingarten.de:
  psql.prod.ff-weingarten.de:
  rproxy.prod.feuerwehr.weingarten.local:
  children:
    docker:
      hosts:
        docker.prod.ff-weingarten.de:
    jump:
      hosts:
        jump.prod.ff-weingarten.de:
    psql:
      hosts:
        psql.prod.ff-weingarten.de:
    nginx:
      hosts:
        rproxy.prod.feuerwehr.weingarten.local: