---
roles:
  - name: alvistack.confluence
  - name: geerlingguy.ntp
  - name: geerlingguy.apache
  - name: geerlingguy.php
  # - name: geerlingguy.mysql
  - name: fauust.mariadb
collections:
  - name: devsec.hardening
  - name: community.windows
  - name: community.mysql
  - name: chocolatey.chocolatey
