---
- name: Create a heimdall directory if it does not exist
  ansible.builtin.file:
    path: /srv/heimdall
    state: directory
    mode: '0755'

- name: Copy docker compose
  ansible.builtin.template:
    src: files/heimdall_prod.docker-compose.j2
    dest: /srv/heimdall/docker-compose.yml
    mode: '0750'

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: /srv/heimdall
    build: always
  register: heimdalloutput

- name: Show results
  ansible.builtin.debug:
    var: heimdalloutput