---
- name: Include tasks for docker installation
  ansible.builtin.include_tasks: install_docker.yml
  when: install_docker

#- name: Include tasks for taiga
#  ansible.builtin.include_tasks: taiga.yml

- name: Include tasks for traccar
  ansible.builtin.include_tasks: traccar.yml

- name: Include tasks for rustdesk_prod
  ansible.builtin.include_tasks: rustdesk.yml

#- name: Include tasks for bookstack_test
#  ansible.builtin.include_tasks: bookstack.yml

- name: Copy backup script
  ansible.builtin.template:
    src: files/docker_backup.j2
    dest: /etc/cron.daily/docker_backup
    mode: '0750'
  when: install_backup
