---
- name: "Set timestamp for the backups"
  ansible.builtin.set_fact:
    now: '{{ lookup("pipe", "date +%F-%T") }}'

- name: Create ad-hoc directory
  ansible.builtin.file:
    path: "{{ nfs_mountpoint }}/ad-hoc"
    state: directory
    mode: '0755'

- name: Backup Databases
  community.mysql.mysql_db:
    state: dump
    name: "{{ item }}"
    target: "/tmp/{{ item }}.sql"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true
  with_items: "{{ mariadb_backup_db_name }}"

# Copy single DB Backups to backup NFS Share
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: "/tmp/{{ item }}.sql"
    dest: "{{ nfs_mountpoint }}/ad-hoc/"
    remote_src: true
    mode: '0644'
  with_items: "{{ mariadb_backup_db_name }}"

# Copy all single DB Backups to local machine:
- name: Pull DB backup
  ansible.builtin.fetch:
    src: "/tmp/{{ item }}.sql"
    dest: /tmp
    fail_on_missing: true
    validate_checksum: true
  with_items: "{{ mariadb_backup_db_name }}"

- name: Remove remote backup
  ansible.builtin.file:
    path: /tmp/backup.sql.gz
    state: absent
