---
- name: Create a traccar directory if it does not exist
  ansible.builtin.file:
    path: /srv/traccar_prod
    state: directory
    mode: '0755'

- name: Copy traccar docker-compose file
  ansible.builtin.template:
    src: templates/traccar.docker-compose.j2
    dest: /srv/traccar_prod/docker-compose.yml
    mode: '0644'
  register: compose_result
  changed_when: "compose_result.changed == true"
  notify: Restart Traccar

- name: Copy traccar traccar.xml file
  ansible.builtin.template:
    src: templates/traccar.xml.j2
    dest: /srv/traccar_prod/traccar.xml
    mode: '0644'
  register: xml_result
  changed_when: "xml_result.changed == true"
  notify: Restart Traccar

- name: Create and start traccar services
  community.docker.docker_compose_v2:
    project_src: /srv/traccar_prod
    build: policy
    pull: missing
    recreate: auto
  register: traccarprodoutput

- name: Copy log deletion script
  ansible.builtin.template:
    src: templates/traccar-clean.j2
    dest: /etc/cron.daily/traccar_clean
    mode: '0750'

- name: Show results
  ansible.builtin.debug:
    var: traccarprodoutput
  when: docker_debug
