---
- name: Update Portainer Container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:2.33.2
    restart_policy: "always"
    published_ports:
      - 9001:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: "--http-enabled"
    pull: missing
    state: started
    # restart: true
    # recreate: true
    comparisons:
      image: strict
      env: strict

- name: Remove password file
  ansible.builtin.file:
    path: /tmp/portainer_password.pwd
    state: absent
