---
- name: Install nfs debian package
  ansible.builtin.apt:
    pkg: nfs-common
    state: present
  when: ansible_os_family == 'Debian'

- name: Check if the mountpoint exists
  ansible.builtin.file:
    path: "{{ nfs_mountpoint }}"
    state: directory
    mode: "{{ nfs_permissions }}"
    owner: root
    group: root

- name: Mount nfs share
  ansible.posix.mount:
    src: "{{ nfs_src }}"
    path: "{{ nfs_mountpoint }}"
    fstype: nfs
    opts: "{{ nfs_options }}"
    state: mounted
