---
- name: "Copy Backup file"
  ansible.builtin.copy:
    src: "{{ nfs_mountpoint }}/ad-hoc/{{ backup_file }}"
    dest: "/tmp/"
    remote_src: true
    mode: '0644'

- name: Restore database
  community.mysql.mysql_db:
    name: all
    state: import
    login_unix_socket: /var/run/mysqld/mysqld.sock
    target: "/tmp/{{ backup_file }}"
  become: true

- name: "Remove copied backup"
  ansible.builtin.file:
    path: "/tmp/{{ backup_file }}"
    state: absent
