---
- name: Create a bookstack directory if it does not exist
  ansible.builtin.file:
    path: /srv/bookstack
    state: directory
    mode: '0755'

- name: Copy docker compose
  ansible.builtin.template:
    src: templates/bookstack.docker-compose.j2
    dest: /srv/bookstack/docker-compose.yml
    mode: '0750'
  register: compose_result
  changed_when: "compose_result.changed == true"
  notify: Restart Bookstack

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: /srv/bookstack
    build: always
    pull: always
    recreate: auto
  register: bookstacktestoutput

- name: Copy .env file
  ansible.builtin.template:
    src: templates/bookstack.env.j2
    dest: /var/lib/docker/volumes/bookstack_bookstack_app_data/_data/www/.env
    mode: '0705'
  register: env_result
  changed_when: "env_result.changed == true"
  notify: Restart Bookstack

- name: Show results
  ansible.builtin.debug:
    var: bookstacktestoutput
