#!/bin/bash
  
MARIADB_DUMP=$(command -v mariadb-dump)
FIND=$(command -v find)
USER_NAME="root"
DATABASE="rainloop"

BASEDIR="/mnt/web_backup/rainloopDB"
BACKUP_NAME="${BASEDIR}$(date +%Y)/db01-rainloop-$(date +%F).sql"

if [ ! -d "${BASEDIR}$(date +%Y)" ]; then
        mkdir "${BASEDIR}$(date +%Y)"
fi

(${MARIADB_DUMP} -u ${USER_NAME} --password="" ${DATABASE}) > "${BACKUP_NAME}"
${FIND} ${BASEDIR}* -mtime +120 -exec rm {} \; || true
