---
- name: Get files in DB Backup folder
  ansible.builtin.find:
    paths: "{{ mountpoint }}"
    recurse: true
    patterns: "*.fbb"
  register: found_files

- name: Get latest file
  ansible.builtin.set_fact:
    latest_file: "{{ found_files.files | sort(attribute='mtime', reverse=true) | first }}"
  register: db_backup

- name: Debug output
  ansible.builtin.debug:
    msg: "Using DB backup: {{ db_backup.ansible_facts.latest_file.path }}"

- name: Restore Database
  ansible.builtin.shell: "/usr/bin/gbak -REP -o -v -USER {{ firebird_database_user }} -PASSWORD {{ firebird_database_user_password }} {{ db_backup.ansible_facts.latest_file.path }} {{ firebird_db_path }}/{{ firebird_db_name }}"

- name: Restore Database Ownership
  ansible.builtin.file:
    path: "{{ firebird_db_path }}/{{ firebird_db_name }}"
    owner: firebird
    group: firebird
