---
- name: Create a netboot directory if it does not exist
  ansible.builtin.file:
    path: "{{ netboot_dir }}"
    state: directory
    mode: '0755'
  tags: [config]

- name: Copy docker compose
  ansible.builtin.template:
    src: templates/netboot.xyz.j2
    dest: "{{ netboot_dir }}/docker-compose.yml"
    mode: "{{ netboot_compose_mode }}"
  notify: Restart Netboot
  tags: [config]

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ netboot_dir }}"
    build: policy
    pull: policy
    recreate: auto
  register: netbootoutput
  tags: [service]

- name: Show results
  ansible.builtin.debug:
    var: netbootoutput
  when: docker_debug
  tags: [debug]
