---
- name: Create needed directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    # - "/mnt/media"
    - "{{ jellyfin_installation_directory }}"
    - "{{ jellyfin_installation_directory }}/config"
    - "{{ jellyfin_installation_directory }}/cache"


- name: Copy docker compose
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ jellyfin_installation_directory }}/docker-compose.yml"
    mode: '0750'

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ jellyfin_installation_directory }}"
    build: always
    pull: policy
    recreate: auto
  register: jellyfinoutput

- name: Show results
  ansible.builtin.debug:
    var: jellyfinoutput
  when: docker_debug
