---
# Role to install docker
- name: Install docker
  become: true
  hosts: docker
  remote_user: ffweingarten
  gather_facts: true
  roles:
    - common
    - { role: nfs, tags: [nfs] }
    - { role: docker, tags: [docker] }
    - { role: portainer, tags: [portainer] }
    - authentik
    - { role: netboot, tags: [netboot] }
    - { role: heimdall, tags: [heimdall] }
    - { role: rustdesk, tags: [rustdesk] }
    - { role: traccar, tags: [traccar] }
    - bookstack
    - { role: nextcloud, tags: [nextcloud] }
    - { role: adminer, tags: [adminer] }
    - taiga
