---
# Role to install docker
- name: Install docker
  become: true
  hosts: docker
  remote_user: ffweingarten
  gather_facts: true
  roles:
    - common
    - nfs
    - docker
    - portainer
    - authentik
    - { role: netboot, tags: [netboot] }
    - heimdall
    - { role: rustdesk, tags: [rustdesk] }
    - traccar
    - bookstack
    - nextcloud
    - { role: adminer, tags: [adminer] }
    - taiga
