---
# Playbook for Firebird Server 3.0 installation

- hosts: prod_draeger, prod_bockermann
  name: Install Firebird 3.0
  remote_user: ffweingarten
  become: true
  become_user: root
  gather_facts: true
  roles:
    - role: devsec.hardening.ssh_hardening
      sftp_enabled: true
    - role: devsec.hardening.os_hardening
    - role: common
      vars:
        setup_qemu: true
    - role: geerlingguy.ntp
    - role: nfs
    - role: firebird
    - role: tribe29.checkmk.agent
