---
- name: Playbook to install a jumphost
  hosts: jump
  remote_user: ffweingarten
  gather_facts: true
  roles:
    - role: common
      become: true
      vars:
        setup_qemu: true
    - role: geerlingguy.ntp
      become: true
    - role: devsec.hardening.ssh_hardening
      become: true
      sftp_enabled: true
    - role: devsec.hardening.os_hardening
      become: true
    - role: jump
    # - role: tribe29.checkmk.agent
