---
# Playbook install software on windows systems

- hosts: windows
  tasks:
    - name: Install multiple software packages
      chocolatey.chocolatey.win_chocolatey:
        name: '{{ item }}'
        state: latest
      loop:
        - procexp
        - putty.portable
        - winscp.install
        - vlc.portable
        - winrar
        - ghostscript.app
        # - atom.install
        - adobereader
        # - atlassian-companion
        - cutepdf
        # - teamviewer-qs
        - vscode.install
        - chocolateygui
        - chocolatey-core.extension
        # - autohotkey.portable
        # - rustdesk.install

    - name: Upgrade installed packages
      chocolatey.chocolatey.win_chocolatey:
        name: all
        state: latest

    - name: Uninstall multiple software packages
      chocolatey.chocolatey.win_chocolatey:
        name:
          - putty
        state: absent

    - name: Gather facts
      chocolatey.chocolatey.win_chocolatey_facts:

    - name: Display the packages
      ansible.builtin.debug:
        var: ansible_chocolatey.packages
