---
# Playbook for updating windows systems

- name: Install Windows Updates
  hosts: windows
  tasks:
    - name: Install and return list of found updates (if any), log to c:\ansible_windows_update.txt
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - Application
          - Definition Updates
        state: installed
        reboot: true
        log_path: c:\ansible_windows_update.txt
      register: win_updates_list
    - name: Output debug information
      vars:
        msg: |
           Installed Updates: {{ win_updates_list.found_update_count }},
           list: {{ win_updates_list.updates }}
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
